#这里配置的是如果符合application的格式，却没有查询到已经存在的环境配置 如写的是application-app.yml而不是 application-test.yml或者application-dev.yml 则会跳出的信息
spring:
  profiles:
    active:
    - dev    
---   
spring:
  profiles: dev #研发环境
  application:
    name: commoncloud-config-lht-dev
---
spring:
  profiles: test #测试环境
  application:
    name: commoncloud-config-lht-test

#请保存为UTF-8格式，否则从git上获取配置时会报错
#配置文件中以 --- 为分隔符