spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: commoncloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root                                          
    password: admin123                                        
    dbcp2:
      min-idle: 5                                           
      initial-size: 5                                      
      max-total: 5                                          
      max-wait-millis: 200
      
devtools:
  restart:
    additional-paths: src/main/java  

logging:
  level:
    com:
      lht:
        springcloud:
          dao: debug


eureka:
  client: 
    service-url:
      defaultZone: http://localhost:7001/eureka 单机环境
  instance:
    instance-id: commoncloud-dept8001
    prefer-ip-address: true

info:
  app.name: lht-commoncloud
  company.name: www.lht.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: commoncloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root                                          
    password: admin123                                        
    dbcp2:
      min-idle: 5                                           
      initial-size: 5                                      
      max-total: 5                                          
      max-wait-millis: 200
      
devtools:
  restart:
    additional-paths: src/main/java  

logging:
  level:
    com:
      lht:
        springcloud:
          dao: debug


eureka:
  client: 
    service-url:
      defaultZone: http://localhost:7001/eureka 单机环境
  instance:
    instance-id: commoncloud-dept8001
    prefer-ip-address: true

info:
  app.name: lht-commoncloud
  company.name: www.lht.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}